services:
  - type: web
    name: ecommerce-backend
    runtime: java
    plan: free
    branch: main
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/e-commerce-website-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: mzBmYCVcdHrhaOSfkMaILDBYlnSKIHCA
      - key: JWT_SECRET
        value: shopeasysecretkeythisisverysecrettobekept12345
