services:
  - type: web
    name: ecommerce-backend
    runtime: docker
    plan: free
    branch: master
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: ""
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: mzBmYCVcdHrhaOSfkMaILDBYlnSKIHCA
      - key: JWT_SECRET
        value: shopeasysecretkeythisisverysecrettobekept12345
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQLDialect
